(function(){
  const TYPES=[
    {id:"ruby",name:"Ruby",letter:"R",color:"#ef4444"},{id:"sapphire",name:"Sapphire",letter:"S",color:"#3b82f6"},{id:"emerald",name:"Emerald",letter:"E",color:"#22c55e"},{id:"amethyst",name:"Amethyst",letter:"A",color:"#a855f7"},{id:"topaz",name:"Topaz",letter:"T",color:"#f59e0b"},{id:"diamond",name:"Diamond",letter:"D",color:"#06d4f7"}];
  const LEVELS=[{n:3,each:3,limit:12,wild:0,locked:0},{n:4,each:3,limit:15,wild:1,locked:0},{n:4,each:4,limit:20,wild:1,locked:2},{n:5,each:4,limit:26,wild:2,locked:3},{n:6,each:4,limit:32,wild:2,locked:5}];
  const $=id=>document.getElementById(id),els=["board","sparks","level","score","moves","combo","limit","status","overlay","overTitle","overMsg","stars","modalStats","restartOverlay"].reduce((a,id)=>(a[id]=$(id),a),{});
  let level=+H5GV.store.get("gem-sort-level",1),gems=[],score=0,moves=0,combo=1,selected=null,paused=true;
  const cfg=()=>LEVELS[Math.min(level-1,LEVELS.length-1)];
  function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
  function uid(){return Date.now()+"-"+Math.random().toString(16).slice(2)}
  function start(){const c=cfg(),types=TYPES.slice(0,c.n);gems=[];types.forEach(t=>{for(let i=0;i<c.each;i++)gems.push({uid:uid(),type:t.id,placed:false,locked:false,wild:false})});for(let i=0;i<c.wild;i++)gems.push({uid:uid(),type:"wild",placed:false,locked:false,wild:true});shuffle(gems);gems.slice(0,c.locked).forEach(g=>g.locked=true);score=0;moves=0;combo=1;selected=null;paused=false;els.overlay.classList.remove("show");render();status("Sort the loose gems into matching trays.")}
  function stats(){els.level.textContent=level;els.score.textContent=score;els.moves.textContent=moves;els.combo.textContent="x"+combo;els.limit.textContent=cfg().limit}
  function typeOf(id){return TYPES.find(t=>t.id===id)||{id:"wild",name:"Star",letter:"*",color:"#fbbf24"}}
  function render(){stats();const c=cfg(),types=TYPES.slice(0,c.n);els.board.innerHTML='<section class="gem-pool"><h2>Loose gems</h2><div class="gem-list"></div></section><section class="gem-trays"></section>';const list=els.board.querySelector(".gem-list"),trays=els.board.querySelector(".gem-trays");gems.filter(g=>!g.placed).forEach(g=>list.appendChild(gemNode(g)));types.forEach(t=>{const placed=gems.filter(g=>g.placed&&g.target===t.id).length,need=c.each;const tray=document.createElement("button");tray.type="button";tray.className="tray"+(placed>=need?" done":"");tray.dataset.type=t.id;tray.innerHTML=`<h3>${t.name}<span>${placed}/${need}</span></h3><div class="tray-list"></div>`;tray.addEventListener("click",()=>selected&&place(selected,t.id));tray.addEventListener("dragover",e=>{e.preventDefault();tray.classList.add("hot")});tray.addEventListener("dragleave",()=>tray.classList.remove("hot"));tray.addEventListener("drop",e=>{e.preventDefault();tray.classList.remove("hot");place(e.dataTransfer.getData("text/plain"),t.id)});gems.filter(g=>g.placed&&g.target===t.id).forEach(g=>tray.querySelector(".tray-list").appendChild(gemNode(g,true)));trays.appendChild(tray)})}
  function gemNode(g,small){const t=typeOf(g.type),b=document.createElement("button");b.type="button";b.className=`gem ${g.wild?"wild":""} ${g.locked?"locked":""} ${selected===g.uid?"selected":""}`;b.style.setProperty("--gem",t.color);b.dataset.letter=t.letter;b.draggable=!small&&!g.locked;b.setAttribute("aria-label",(g.locked?"Locked ":"")+t.name);if(!small){b.addEventListener("click",()=>select(g));b.addEventListener("dragstart",e=>{if(g.locked){e.preventDefault();return}selected=g.uid;e.dataTransfer.setData("text/plain",g.uid)})}return b}
  function select(g){if(paused)return;if(g.locked){status("This gem is locked until you sort another gem.");H5GV.audio.wrong();return}selected=selected===g.uid?null:g.uid;H5GV.audio.click();render()}
  function place(uid,type){if(paused)return;const g=gems.find(x=>x.uid===uid&&!x.placed);if(!g||g.locked)return;moves++;const ok=g.type===type||g.wild;if(ok){g.placed=true;g.target=type;score+=100*combo+(g.wild?40:0);combo=Math.min(9,combo+1);selected=null;unlockOne();H5GV.audio.correct();status(`${typeOf(g.type).name} placed.`);if(trayDone(type))burst(type)}else{combo=1;score=Math.max(0,score-25);H5GV.audio.wrong();status(`${typeOf(g.type).name} needs a different tray.`)}if(moves>=cfg().limit&&gems.some(x=>!x.placed))return fail();render();if(gems.every(x=>x.placed))win()}
  function trayDone(type){return gems.filter(g=>g.placed&&g.target===type).length===cfg().each}
  function unlockOne(){const g=gems.find(x=>x.locked);if(g)g.locked=false}
  function burst(type){const tray=[...document.querySelectorAll(".tray")].find(t=>t.dataset.type===type),r=(tray||els.board).getBoundingClientRect(),p=els.sparks.getBoundingClientRect();for(let i=0;i<18;i++){const s=document.createElement("i");s.className="spark";s.style.left=(r.left-p.left+r.width/2)+"px";s.style.top=(r.top-p.top+r.height/2)+"px";s.style.setProperty("--c",typeOf(type).color);s.style.setProperty("--x",(Math.random()*160-80)+"px");s.style.setProperty("--y",(Math.random()*140-70)+"px");els.sparks.appendChild(s);setTimeout(()=>s.remove(),800)}}
  function status(t){els.status.textContent=t}
  function win(){paused=true;H5GV.audio.done();H5GV.store.set("gem-sort-level",Math.min(level+1,LEVELS.length));els.overTitle.textContent=`Level ${level} complete`;els.overMsg.textContent="The vault trays are sparkling.";els.stars.textContent=moves<=cfg().limit-5?"★★★":moves<=cfg().limit-2?"★★☆":"★☆☆";els.modalStats.textContent=`Score ${score} · Moves ${moves} · Combo x${combo}`;els.restartOverlay.textContent=level>=LEVELS.length?"Replay":"Next Level";els.overlay.classList.add("show");if(level<LEVELS.length)level++}
  function fail(){paused=true;H5GV.audio.wrong();els.overTitle.textContent="No moves left";els.overMsg.textContent="Replay the level and keep the combo chain tidy.";els.stars.textContent="★☆☆";els.modalStats.textContent=`Score ${score} · Moves ${moves}`;els.restartOverlay.textContent="Try Again";els.overlay.classList.add("show")}
  $("nextBtn").addEventListener("click",start);els.restartOverlay.addEventListener("click",start);H5GV.wireCommonControls({onRestart:start,onPause:()=>{paused=!paused;$("pauseBtn").textContent=paused?"Resume":"Pause";status(paused?"Paused.":"Sorting resumed.")}});
  stats();
})();
