(function(){
  const canvas=document.getElementById("game"),ctx=canvas.getContext("2d"),prev=document.getElementById("preview"),pctx=prev.getContext("2d");
  const W=canvas.width,H=canvas.height,IMGW=480,IMGH=360,ox=140,oy=92;
  const $=id=>document.getElementById(id),els=["pieces","moves","time","zoom","status","overlay","overTitle","overMsg","stars","modalStats","restartOverlay","difficulty"].reduce((a,id)=>(a[id]=$(id),a),{});
  let pieces=[],cols=4,rows=3,moves=0,seconds=0,scale=1,pan={x:0,y:0},drag=null,paused=true,timer,scene=0;
  function gridFor(n){return n===12?[4,3]:n===24?[6,4]:n===48?[8,6]:[12,8]}
  function drawArt(c,w,h,variant){const g=c.createLinearGradient(0,0,w,h);g.addColorStop(0,["#06d4f7","#22c55e","#fbbf24"][variant%3]);g.addColorStop(1,["#312e81","#0f766e","#ec4899"][variant%3]);c.fillStyle=g;c.fillRect(0,0,w,h);c.fillStyle="rgba(255,255,255,.16)";for(let i=0;i<14;i++){c.beginPath();c.arc((i*73+variant*41)%w,(i*47+80)%h,28+(i%4)*9,0,Math.PI*2);c.fill()}c.fillStyle="#071426";c.globalAlpha=.25;for(let i=0;i<9;i++){c.fillRect((i*97)%w,(i*53)%h,130,18)}c.globalAlpha=1;c.fillStyle="rgba(255,255,255,.72)";c.font="700 32px Space Grotesk";c.fillText(["NEON HARBOR","ORBIT GARDEN","SUNSET GRID"][variant%3],26,h-34)}
  function imageCanvas(){const off=document.createElement("canvas");off.width=IMGW;off.height=IMGH;drawArt(off.getContext("2d"),IMGW,IMGH,scene);return off}
  let img=imageCanvas();
  function start(){[cols,rows]=gridFor(+els.difficulty.value);scene=(scene+1)%3;img=imageCanvas();drawArt(pctx,prev.width,prev.height,scene);pieces=[];moves=0;seconds=0;scale=1;pan={x:0,y:0};paused=false;const pw=IMGW/cols,ph=IMGH/rows;for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){pieces.push({x,y,w:pw,h:ph,cx:ox+x*pw,cy:oy+y*ph,px:30+Math.random()*(W-pw-60),py:30+Math.random()*(H-ph-60),locked:false})}shuffle(pieces);els.overlay.classList.remove("show");clearInterval(timer);timer=setInterval(()=>{if(!paused){seconds++;stats()}},1000);stats();draw()}
  function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
  function stats(){const done=pieces.filter(p=>p.locked).length,all=pieces.length;els.pieces.textContent=Math.round(done/all*100)+"%";els.moves.textContent=moves;els.time.textContent=H5GV.formatTime(seconds);els.zoom.textContent=Math.round(scale*100)+"%"}
  function world(e){const r=canvas.getBoundingClientRect();return{x:((e.clientX-r.left)*W/r.width-pan.x)/scale,y:((e.clientY-r.top)*H/r.height-pan.y)/scale}}
  function pick(pos){for(let i=pieces.length-1;i>=0;i--){const p=pieces[i];if(!p.locked&&pos.x>=p.px&&pos.x<=p.px+p.w&&pos.y>=p.py&&pos.y<=p.py+p.h)return p}return null}
  function down(e){if(paused)return;canvas.setPointerCapture(e.pointerId);const pos=world(e),p=pick(pos);if(p){pieces=pieces.filter(x=>x!==p);pieces.push(p);drag={p,dx:pos.x-p.px,dy:pos.y-p.py,moved:false}}else drag={pan:true,x:e.clientX,y:e.clientY,px:pan.x,py:pan.y}}
  function move(e){if(!drag||paused)return;if(drag.pan){pan.x=drag.px+e.clientX-drag.x;pan.y=drag.py+e.clientY-drag.y}else{const pos=world(e);drag.p.px=pos.x-drag.dx;drag.p.py=pos.y-drag.dy;drag.moved=true}draw()}
  function up(){if(!drag||paused)return;if(drag.p&&drag.moved){moves++;const p=drag.p,d=Math.hypot(p.px-p.cx,p.py-p.cy);if(d<24){p.px=p.cx;p.py=p.cy;p.locked=true;H5GV.audio.correct();els.status.textContent="Piece snapped into place."}else H5GV.audio.click();if(pieces.every(x=>x.locked))win()}drag=null;stats();draw()}
  function draw(){ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,W,H);const bg=ctx.createLinearGradient(0,0,0,H);bg.addColorStop(0,"#10213f");bg.addColorStop(1,"#071426");ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);ctx.setTransform(scale,0,0,scale,pan.x,pan.y);ctx.strokeStyle="rgba(255,255,255,.45)";ctx.lineWidth=2/scale;ctx.strokeRect(ox,oy,IMGW,IMGH);ctx.globalAlpha=.16;ctx.drawImage(img,ox,oy,IMGW,IMGH);ctx.globalAlpha=1;pieces.forEach(p=>{ctx.save();ctx.beginPath();ctx.roundRect(p.px,p.py,p.w,p.h,8);ctx.clip();ctx.drawImage(img,p.x*p.w,p.y*p.h,p.w,p.h,p.px,p.py,p.w,p.h);ctx.restore();ctx.strokeStyle=p.locked?"#34d399":"rgba(255,255,255,.38)";ctx.lineWidth=p.locked?3/scale:1.5/scale;ctx.strokeRect(p.px,p.py,p.w,p.h)});ctx.setTransform(1,0,0,1,0,0)}
  function win(){paused=true;clearInterval(timer);H5GV.audio.done();const par=pieces.length*2,star=moves<=par?"★★★":moves<=par*1.5?"★★☆":"★☆☆";els.overTitle.textContent="Puzzle complete";els.overMsg.textContent="The scene is whole again.";els.stars.textContent=star;els.modalStats.textContent=`${pieces.length} pieces · ${moves} moves · ${H5GV.formatTime(seconds)}`;els.restartOverlay.textContent="Next Puzzle";els.overlay.classList.add("show")}
  function zoom(v){scale=Math.max(.65,Math.min(1.8,scale+v));stats();draw()}
  canvas.addEventListener("pointerdown",down);canvas.addEventListener("pointermove",move);canvas.addEventListener("pointerup",up);canvas.addEventListener("pointercancel",up);
  $("newBtn").addEventListener("click",start);els.restartOverlay.addEventListener("click",start);$("zoomIn").addEventListener("click",()=>zoom(.15));$("zoomOut").addEventListener("click",()=>zoom(-.15));$("centerBtn").addEventListener("click",()=>{pan={x:0,y:0};scale=1;stats();draw()});
  H5GV.wireCommonControls({onRestart:start,onPause:()=>{paused=!paused;$("pauseBtn").textContent=paused?"Resume":"Pause";els.status.textContent=paused?"Paused.":"Puzzle resumed.";draw()}});
  if(!CanvasRenderingContext2D.prototype.roundRect){CanvasRenderingContext2D.prototype.roundRect=function(x,y,w,h,r){this.moveTo(x+r,y);this.arcTo(x+w,y,x+w,y+h,r);this.arcTo(x+w,y+h,x,y+h,r);this.arcTo(x,y+h,x,y,r);this.arcTo(x,y,x+w,y,r);return this}}
  drawArt(pctx,prev.width,prev.height,0);draw();
})();
