/* Clue text for every word used across the shipped Mini Crossword grids.
   Kept separate from the grid data so new grids can be added without
   touching this file, as long as every one of their words gets an entry. */
window.CLUES = {
  act: "Put on a show",
  adapt: "Adjust to new conditions",
  aisle: "Supermarket walkway",
  alas: "Sadly",
  along: "In the company of",
  alto: "Voice between soprano and tenor",
  amass: "Gather in quantity",
  anew: "Once again, from scratch",
  ankle: "Joint above the foot",
  ante: "Poker stake, before the deal",
  anti: "Opposed to",
  area: "Region or extent",
  aroma: "Pleasant smell",
  avert: "Ward off",
  cedar: "Fragrant evergreen wood",
  cent: "Hundredth of a dollar",
  deed: "Legal document, or an act",
  donut: "Ring-shaped fried pastry",
  dwarf: "Make seem small by comparison",
  each: "Every one",
  earth: "The planet we live on",
  elk: "Large deer of the north",
  else: "Otherwise",
  elude: "Escape or evade cleverly",
  erase: "Rub out",
  erupt: "Burst out suddenly, like a volcano",
  ever: "At any time",
  eye: "Organ of sight",
  fed: "Gave food to",
  flea: "Tiny jumping bloodsucker",
  gecko: "Wall-climbing lizard",
  glee: "Great delight",
  goose: "Honking farm bird",
  grain: "Cereal seed, or a texture in wood",
  green: "Colour of grass",
  haste: "Hurry",
  hate: "Strongly dislike",
  heft: "Weight, or to lift with effort",
  her: "Belonging to that woman",
  idea: "A thought or plan",
  idiot: "Fool",
  inept: "Lacking skill",
  iron: "Metal used for pressing shirts",
  larva: "Insect's early stage",
  leafy: "Full of foliage",
  led: "Guided, past tense",
  leg: "Limb for walking",
  lest: "For fear that",
  lye: "Caustic substance used in soap-making",
  mad: "Angry, or insane",
  manor: "Large country estate",
  midst: "In the middle of",
  mode: "Style or manner",
  must: "Have to",
  name: "What you're called",
  nap: "Short daytime sleep",
  natal: "Relating to birth",
  net: "Woven mesh, or profit after costs",
  new: "Not old",
  news: "Current events reporting",
  nicer: "More pleasant, comparative",
  nip: "Small bite, or a pinch of cold",
  nobly: "In a noble manner",
  nod: "Small downward tilt of the head, agreeing",
  nosy: "Overly curious about others",
  note: "Short written message",
  oath: "Solemn promise",
  ocean: "Vast body of salt water",
  ode: "Poem of praise",
  odor: "Smell",
  okay: "Fine, all right",
  omen: "Sign of things to come",
  oral: "Spoken, not written",
  peg: "Clip for hanging washing",
  petal: "Colourful part of a flower",
  pill: "Small tablet of medicine",
  plod: "Walk slowly and heavily",
  plot: "Storyline, or a small patch of land",
  posse: "Group deputised to give chase",
  pray: "Speak to a higher power",
  puree: "Food blended to a smooth pulp",
  rag: "Torn cloth for cleaning",
  rant: "Angry, drawn-out complaint",
  rasp: "Harsh, grating sound",
  renal: "Relating to the kidneys",
  rich: "Having great wealth",
  rim: "Outer edge of something round",
  rosy: "Optimistic, or pink-tinged",
  rot: "Decay",
  rye: "Grain used in bread and whiskey",
  sake: "Purpose or benefit, as in 'for its own ___'",
  scare: "Give a fright",
  sled: "Vehicle for sliding over snow",
  snake: "Legless reptile",
  sneak: "Move quietly and secretly",
  stair: "One step of a staircase",
  stale: "No longer fresh",
  steel: "Strong alloy of iron and carbon",
  stool: "Backless single seat",
  sweat: "Perspire",
  taboo: "Forbidden by social custom",
  taken: "Already occupied, or captured",
  tan: "Skin colour after sun exposure",
  taps: "Light knocks, or faucets",
  tea: "Hot drink brewed from leaves",
  tease: "Playfully provoke",
  tenor: "High male singing voice",
  terse: "Brief to the point of curtness",
  the: "Definite article",
  these: "Plural of 'this'",
  thief: "One who steals",
  ton: "2,000 pounds",
  tree: "Tall woody plant",
  trek: "Long, arduous journey",
  troop: "Group of soldiers or scouts",
  tugs: "Pulls sharply",
  tyke: "Small, mischievous child",
  type: "Sort or category",
  union: "Coming together as one",
  unwed: "Not married",
  vase: "Container for cut flowers",
  vat: "Large tank for liquids",
  visa: "Travel document permitting entry",
  worry: "Feel uneasy about something",
  yelp: "Short, sharp cry",
  ape: "Chimp or gorilla, broadly",
  arch: "Curved structural support",
  crude: "Unrefined, or tastelessly blunt",
  edge: "Sharp border, or a slight advantage",
  eel: "Long, snake-like fish",
  hedge: "Trimmed row of bushes as a boundary",
  pure: "Not mixed with anything else",
  reel: "Stagger, or a fishing spool",
  ruler: "Straight edge for measuring, or a monarch",
};
