(function(){
  const countries=window.H5GVCountries.slice().sort((a,b)=>a.name.localeCompare(b.name));const $=id=>document.getElementById(id);
  const els=["mode","guessCount","time","best","streak","map","markers","hint","guessForm","guessInput","countriesList","history","giveUpBtn","newBtn","winPct","avg","bestStreak"].reduce((a,id)=>(a[id]=$(id),a),{});
  let target,guesses=[],seconds=0,timer,over=false;const stats=()=>H5GV.store.get("world-guess-stats",{played:0,wins:0,totalGuesses:0,best:null,streak:0,bestStreak:0,lastDaily:null});
  function saveStats(s){H5GV.store.set("world-guess-stats",s)}
  function dailyIndex(){const d=new Date(),key=Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate())/86400000;return key%countries.length}
  function start(){target=els.mode.value==="daily"?countries[dailyIndex()]:countries[Math.floor(Math.random()*countries.length)];guesses=[];seconds=0;over=false;clearInterval(timer);timer=setInterval(()=>{if(!over){seconds++;drawStats()}},1000);els.hint.textContent="Mystery Country: hidden";els.guessInput.value="";renderMarkers();renderHistory();drawStats()}
  function project(c){return{x:(c.longitude+180)/360*900,y:(90-c.latitude)/180*460}}
  function hav(a,b){const R=6371,rad=x=>x*Math.PI/180,dLat=rad(b.latitude-a.latitude),dLon=rad(b.longitude-a.longitude),la1=rad(a.latitude),la2=rad(b.latitude);const h=Math.sin(dLat/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dLon/2)**2;return Math.round(2*R*Math.asin(Math.sqrt(h)))}
  function bucket(d){if(d===0)return"correct";if(d<900)return"very-close";if(d<2200)return"close";if(d<5000)return"medium";if(d<9000)return"far";return"very-far"}
  function renderMarkers(){els.markers.innerHTML="";countries.forEach(c=>{const p=project(c),g=guesses.find(x=>x.iso2===c.iso2),m=document.createElementNS("http://www.w3.org/2000/svg","circle");m.setAttribute("cx",p.x);m.setAttribute("cy",p.y);m.setAttribute("r",g?7:4);m.setAttribute("tabindex","0");m.setAttribute("class","country-marker "+(g?"m-"+g.bucket:"unguessed"));m.setAttribute("aria-label",g?`${c.name}, ${g.distance} km away`:c.name);m.addEventListener("click",()=>{els.guessInput.value=c.name;els.guessInput.focus()});m.appendChild(document.createElementNS("http://www.w3.org/2000/svg","title")).textContent=c.name;els.markers.appendChild(m)})}
  function renderHistory(){els.history.innerHTML="";guesses.slice().reverse().forEach(g=>{const li=document.createElement("li");li.innerHTML=`<strong>${g.name}</strong><span>${g.distance.toLocaleString()} km · ${label(g.bucket)}</span>`;els.history.appendChild(li)})}
  function label(b){return({correct:"Correct", "very-close":"Very close", close:"Close", medium:"Medium", far:"Far", "very-far":"Very far"})[b]}
  function drawStats(){const s=stats();els.guessCount.textContent=guesses.length;els.time.textContent=H5GV.formatTime(seconds);els.best.textContent=s.best||"--";els.streak.textContent=s.streak;els.winPct.textContent=s.played?Math.round(s.wins/s.played*100)+"%":"0%";els.avg.textContent=s.wins?(s.totalGuesses/s.wins).toFixed(1):"--";els.bestStreak.textContent=s.bestStreak}
  function guess(name){if(over)return;const c=countries.find(x=>x.name.toLowerCase()===name.trim().toLowerCase());if(!c){els.hint.textContent="Choose a country from the list.";H5GV.audio.wrong();return}if(guesses.some(g=>g.iso2===c.iso2)){els.hint.textContent="You already tried that country.";return}const d=hav(c,target),b=bucket(d),entry={...c,distance:d,bucket:b};guesses.push(entry);H5GV.audio.correct();els.hint.textContent=d===0?`Correct: ${target.name}.`:`Your guess was approximately ${d.toLocaleString()} km away. ${label(b)}.`;els.guessInput.value="";renderMarkers();renderHistory();if(d===0)win();drawStats()}
  function win(){over=true;clearInterval(timer);H5GV.audio.done();const s=stats(),today=new Date().toISOString().slice(0,10);s.played++;s.wins++;s.totalGuesses+=guesses.length;s.best=s.best?Math.min(s.best,guesses.length):guesses.length;if(els.mode.value==="daily"&&s.lastDaily!==today){s.streak++;s.lastDaily=today}else if(els.mode.value==="random")s.streak++;s.bestStreak=Math.max(s.bestStreak,s.streak);saveStats(s);els.hint.textContent=`Solved: ${target.name} in ${guesses.length} guesses and ${H5GV.formatTime(seconds)}.`;drawStats()}
  function giveUp(){if(over)return;over=true;clearInterval(timer);const s=stats();s.played++;s.streak=0;saveStats(s);els.hint.textContent=`The mystery country was ${target.name}.`;guesses.push({...target,distance:0,bucket:"correct"});renderMarkers();renderHistory();drawStats()}
  countries.forEach(c=>{const o=document.createElement("option");o.value=c.name;els.countriesList.appendChild(o)});els.guessForm.addEventListener("submit",e=>{e.preventDefault();guess(els.guessInput.value)});els.giveUpBtn.addEventListener("click",giveUp);els.newBtn.addEventListener("click",()=>{els.mode.value="random";start()});els.mode.addEventListener("change",start);H5GV.wireCommonControls({});
  start();
})();
